<script lang="ts" setup>

</script>

<template>
  <div class="min-h-full px-3 align-items-center justify-content-center">
    <h1 id="privacy-policy">
      Privacy Policy
    </h1><p><em>Last Modified: 14 April 2023</em></p><p>Thank you for your interest in Supabase, Inc., ("<strong><em>Supabase</em></strong>," "<strong><em>we</em></strong>", "<strong><em>our</em></strong>" or "<strong><em>us</em></strong>"). Supabase provides a suite of open source tools, stitched together to build a seamless developer experience. This Privacy Notice explains how information about you, that directly identifies you, or that makes you identifiable ("<strong><em>personal information</em></strong>") is collected, used and disclosed by Supabase in connection with our website at <a href="https://supabase.com">supabase.com</a> (the "<strong><em>Site</em></strong>") and our services offered in connection with the Site (collectively with the Site, the "<strong><em>Service</em></strong>").</p><p>We may also provide you with additional privacy notices or disclosures where the scope of the inquiry, request, or personal information we require falls outside the scope of this Privacy Notice. In that case, the additional Privacy Notice or disclosures will govern how we may process the information you provide at that time. Please note that this Privacy Notice does not cover or apply to our processing of information about our employees or contractors.</p><p>This Policy explains how we use your personal information when we act as a data controller. As far as you use our Service as a natural person, we are the controller of your personal information. We are responsible for, and control, the processing of your personal information.</p><p>Wherever our customers use our Service to submit, manage, or otherwise use content relating to our customers’ end users ("<strong><em>Customer Data</em></strong>") during the provision of our Service, we have contractually committed ourselves to only process such information on behalf and under the instruction of the respective customer, who is the data controller. This Privacy Notice does not apply to such processing and we recommend you read the Privacy Notice of the respective customer, if their processing concerns your personal information.</p><h2 id="region-specific-disclosures">
      Region-specific Disclosures
    </h2><ul>
      <li><strong>California - Your California Privacy Rights:</strong> If you are a California resident, California Civil Code Section 1798.83 permits you to request information regarding the disclosure of personal information to third parties for their direct marketing purposes during the immediately preceding calendar year. Note we do not share your personal information with third parties for their own marketing purposes.</li>
      <li><strong>Nevada:</strong> Chapter 603A of the Nevada Revised Statutes permits a Nevada resident to opt out of future sales of certain covered information that a website operator has collected or will collect about the resident. Note we do not sell your personal information within the meaning of Chapter 603A. However, if you would still like to submit such a request, please contact us at <a href="mailto:support@supabase.io">support@supabase.io</a>.</li>
      <li><strong>European Economic Area, United Kingdom or Switzerland:</strong> If you are located in the European Economic Area ("<strong><em>EEA</em></strong>"), United Kingdom or Switzerland, or otherwise engage with Supabase’s European operations, please see the <strong>Privacy Disclosures for the European Economic Area, United Kingdom and Switzerland</strong> for additional European-specific privacy disclosures, including what constitutes your personal information, the lawful bases we rely on to process your personal information, how we use cookies when you access our Sites from the EEA, UK or Switzerland and your rights in respect of your personal information.</li>
    </ul><p><strong>Note for International Visitors:</strong> Personal information may be transferred to, stored and processed in a country other than the one in which it was collected. For example, the Sites are primarily hosted in and provided from the United States. Please note the country to which personal data is transferred may not provide the same level of protection for personal information as the country from which it was transferred.</p><h2 id="1-information-we-collect-and-our-use">
      1. Information we collect and our use
    </h2><p>We collect personal information in connection with your visits to and use of the Service. This collection includes information that you provide in connection with the Service, information from third parties, and information that is collected automatically such as through the use of cookies and other technologies.</p><h3 id="information-that-you-provide">
      Information That You Provide
    </h3><p>We collect personal information from you. The categories of information we collect can include:</p><ul>
      <li><strong><em>Registration information.</em></strong> We collect personal and/or business information that you provide when you register for an account at the Site. This information may include your name, email address, GitHub username. We use this information to administer your account, provide you with the relevant services and information, communicate with you regarding your account, the Site and for customer support purposes.</li>
      <li><strong><em>Information collected through the Use of the Service.</em></strong> After registration, you may create, upload or transmit files, documents, videos, images, data or information as part of your use of the Service (collectively, "<strong><em>User Content</em></strong>"). User Content and any information contained in the User Content, including personal information you may have included, is stored and collected as part of the Service. You have full control of the information included in the User Content.</li>
      <li><strong><em>Payment information.</em></strong> If you make a purchase or payment on the Site, such as for a subscription, we collect transactional information provided in connection with your purchase or payment. Please note that we use third party payment processors, including Stripe, to process payments made to us. As such, we do not retain any personally identifiable financial information such as credit card numbers. Rather, all such information is provided directly by you to our third-party processor. The payment processor’s use of your personal information is governed by their privacy notice. To view Stripe’s privacy notice, please visit: - <strong><em>Payment information.</em></strong> If you make a purchase or payment on the Site, such as for a subscription, we collect transactional information provided in connection with your purchase or payment. Please note that we use third party payment processors, including Stripe, to process payments made to us. As such, we do not retain any personally identifiable financial information such as credit card numbers. Rather, all such information is provided directly by you to our third-party processor. The payment processor’s use of your personal information is governed by their privacy notice. To view Stripe’s privacy notice, please visit: <a href="https://stripe.com/privacy">https://stripe.com/privacy</a>.</li>
      <li><strong><em>Communications.</em></strong> If you communicate with us through any paper or electronic form, we may collect your name, email address, mailing address, phone number, or any other personal information you choose to provide to us. We use this information to investigate and respond to your inquiries, and to communicate with you, to enhance the services we offer to our users and to manage and grow our organization. If you register for our newsletters or updates, we may communicate with you by email. To unsubscribe from promotional messages, please follow the instructions within our messages and review the <strong>Control Over Your Information</strong> section below. If you become a contributor, we may also collect your GitHub name and feature you on our website.</li>
      <li><strong><em>Inquiries and Feedback.</em></strong> If you contact us, we will collect the information that you provide us, such as your contact information and the contents of your communication with us.</li>
    </ul><p>You are free to choose which personal information you want to provide to us or whether you want to provide us with personal information at all. However, some information, such as your name, address, payment transaction information, and information on your requested Services may be necessary for the performance of our contractual obligations.</p><h3 id="information-from-third-party-sources">
      Information from Third Party Sources
    </h3><p>We may receive personal information about you from our business partners and service providers and combine this information with other data we collect from you. The third-parties may include website and service operators, payment processors, marketing partners, and shipping providers. The information may include contact information, demographic information, information about your communications and related activities, and information about your orders. We may use this information to administer and facilitate our services, your orders and our marketing activities.</p><ul>
      <li><strong><em>Single Sign-On.</em></strong> We use single sign-on ("<strong>SSO</strong>") such as GitHub to allow a user to authenticate their account using one set of login information. We will have access to certain information from those third parties in accordance with the authorization procedures determined by those third parties, including, for example, your name, username, email address, language preference, and profile picture. We use this information to operate, maintain, and provide to you the features and functionality of the Service. We may also send you service-related emails or messages (e.g., account verification, purchase confirmation, customer support, changes or updates to features of the Site, technical and security notices).</li>
      <li><strong><em>Social Media.</em></strong> When you interact with our Site through various social media, such as when you click on the social media icon on the Site, follow us on a social media site, or post a comment to one of our pages, we may receive information from the social network such as your profile information, profile picture, gender, user name, user ID associated with your social media account, age range, language, country, and any other information you permit the social network to share with third parties. The data we receive is dependent upon your privacy settings with the social network. We use this information to operate, maintain, and provide to you the features and functionality of the Service, as well as to communicate directly with you, such as to send you email messages about products and services that may be of interest to you.</li>
      <li><strong><em>Employment Applications.</em></strong> If you apply for employment, we collect your contact and demographic information, educational and work history, employment interests, information obtained during interviews and any other information you choose to provide. We use the information provided to evaluate your candidacy for employment, to communicate with you during the application process and to facilitate the onboarding process.</li>
      <li><strong><em>Information from Other Sources.</em></strong> We may obtain information from other sources, including through third-party information providers, our shareholders, customers, or through transactions such as mergers and acquisitions. We may combine this information with other information we collect from or about you. In these cases, our Privacy Notice governs the handling of the combined personal information. We use this information to operate, maintain, and provide to you the features and functionality of the Service, as well as to communicate directly with you, such as to send you email messages about products and services that may be of interest to you.</li>
    </ul><h3 id="other-uses-of-personal-information">
      Other Uses of Personal Information
    </h3><p>In addition to the uses described above, we may collect and use personal information for the following purposes:</p><ul>
      <li>For our business activities, including to operate the Service and to provide you with the features and functionality of the Service;</li>
      <li>To communicate with you and respond to your requests, such as to respond to your questions, contact you about changes to the Service, and communicate about account related matters;</li>
      <li>For marketing and advertising purposes, such as to market to you or offer you with information and updates on our products or services we think that you may be interested in. While we may use your personal information in this manner, please note that we do not use User Content to serve you ads, and we will never share User Content with any third parties for marketing or advertising purposes, unless you have explicitly submitted it to us for that purpose;</li>
      <li>For analytics and research purposes;</li>
      <li>To enforce our <strong>Terms of Service</strong>, to resolve disputes, to carry out our obligations and enforce our rights, and to protect our business interests and the interests and rights of third parties;</li>
      <li>To comply with contractual and legal obligations and requirements;</li>
      <li>To fulfill any other purpose for which you provide personal information; and</li>
      <li>For any other lawful purpose, or other purpose that you consent to.</li>
    </ul><h2 id="2-how-we-share-personal-information">
      2. How we share personal information
    </h2><p>We may share your personal information in the instances described below. For further information on your choices regarding your information, see <strong>Control Over Your Information</strong>.</p><ul>
      <li>We may share your personal information with third-party service providers or business partners who help us deliver or improve our Site or services, or who perform services on our behalf, which are subject to reasonable confidentiality terms, and may include processing payments, providing web hosting services, or providing analytics.</li>
      <li>Third parties as required by law or subpoena or if we reasonably believe that such action is necessary to (a) comply with the law and the reasonable requests of law enforcement; (b) to enforce our <strong>Terms of Service</strong> or other agreements or to protect the security or integrity of the Supabase services, including to prevent harm or financial loss, or in connection with preventing fraud or illegal activity; and/or (c) to exercise or protect the rights, property, or personal safety of Supabase, our Customers, visitors, or others.</li>
      <li>We may share with other companies and brands owned or controlled by Supabase, and other companies owned by or under common ownership as Supabase. These companies will use your personal information in the same way as we can under this Privacy Notice.</li>
      <li>We may transfer any information we collect in the event we sell or transfer all or a portion of our business or assets (including any shares in the company) or any portion or combination of our products, services, businesses and/or assets. Should such a transaction occur (whether a divestiture, merger, acquisition, bankruptcy, dissolution, reorganization, liquidation, or similar transaction or proceeding), we will use reasonable efforts to ensure that any transferred information is treated in a manner consistent with this Privacy Notice.</li>
      <li>We may disclose your information publicly or with another third party with your prior authorization.</li>
      <li>With others in an aggregated or otherwise anonymized form that does not reasonably identify you directly as an individual.</li>
    </ul><h2 id="3-control-over-your-information">
      3. Control over your information
    </h2><h3 id="email-communications">
      Email Communications
    </h3><p>From time to time, we may send you emails regarding updates to our Service, products or services, notices about our organization, or information about products/services we offer (or promotional offers from third parties) that we think may be of interest to you. If you wish to unsubscribe from such emails, simply click the "unsubscribe link" provided at the bottom of the email communication. Note that you cannot unsubscribe from certain services-related email communications (e.g., account verification, confirmations of transactions, technical or legal notices).</p><h3 id="modifying-account-information">
      Modifying Account Information
    </h3><p>If you have an online account with us, you have the ability to modify certain information in your account (e.g., your contact information) through the account options provided on the Site. If there is personal information in your User Content, you can use the features and functionality of the Service to edit or delete the personal information or User Content. Not all personal information is maintained in a format that you can access or change. If you would like to request access to, or correction or deletion of personal information, you may send your request to us at the email provided below. We will review your request and may require you to provide additional information to identify yourself, but we do not promise that we will be able to satisfy your request.</p><h2 id="4-how-we-use-cookies-and-other-tracking-technology-to-collect-information">
      4. How We Use Cookies and Other Tracking Technology to Collect Information
    </h2><p>We, and our third-party partners, automatically collect certain types of usage information when you visit our Site, read our emails, or otherwise engage with us. &nbsp;We typically collect this information through a variety of tracking technologies, including cookies, web beacons, embedded scripts, location-identifying technologies, file information, and similar technology (collectively, "<strong>tracking technologies</strong>").</p><p>We, and our third-party partners, use tracking technologies to automatically collect usage and device information, such as:</p><ul>
      <li>Information about your device and its software, such as your IP address, browser type, Internet service provider, device type/model/manufacturer, operating system, date and time stamp, and a unique ID that allows us to uniquely identify your browser or your account (including, for example, a persistent device identifier), and other such information.</li>
      <li>When you access our sites from a mobile device, we may collect unique identification numbers associated with your device or our mobile application mobile carrier, device type, model and manufacturer, mobile device operating system brand and model, and depending on your mobile device settings, we may be able to approximate a device’s location by analyzing other information, like an IP address.</li>
      <li>Information about the way you access and use our services, for example, the site from which you came and the site to which you are going when you leave our services, the pages you visit, the links you click, whether you open emails or click the links contained in emails, whether you access the services from multiple devices, and other actions you take on the Sites.</li>
    </ul><p>We use the data collected through tracking technologies to: &nbsp;(a) remember information so that you will not have to re-enter it during your visit or the next time you visit the site; (b) provide custom content and information; (c) identify you across multiple devices; (d) provide and monitor the effectiveness of our services; (e) monitor aggregate metrics such as total number of visitors, traffic, usage, and demographic patterns on our Site; (f) diagnose or fix technology problems; and (g) to provide, plan for, and enhance our services.</p><p><strong>Note we do not engage in online targeted advertising.</strong></p><p><strong>Cookies and Other Tracking Technologies Opt-Out.</strong> Depending on your browser or mobile device, you may be able to set your browser to delete or notify you of cookies and other tracking technology by actively managing the settings on your browser or mobile device.</p><p>If you would prefer not to accept cookies, most browsers will allow you to: (i) change your browser settings to notify you when you receive a cookie, which lets you choose whether or not to accept it; (ii) disable existing cookies; or (iii) set your browser to automatically reject cookies. Please note that doing so may negatively impact your experience using the sites, as some features and services on our sites may not work properly. Depending on your mobile device and operating system, you may not be able to delete or block all cookies. You may also set your e-mail options to prevent the automatic downloading of images that may contain technologies that would allow us to know whether you have accessed our e-mail and performed certain functions with it.</p><h2 id="5-data-retention-and-security">
      5. Data Retention and Security
    </h2><p>We will retain your personal information for the length of time needed to fulfill the purposes outlined in this Privacy Notice, unless a longer retention period is required or permitted by law. We store data on servers in the U.S. or any other country in which Supabase or its affiliates, subsidiaries, agents or contractors maintain facilities. If you are located in the European Union or other regions with laws governing data collection and use that may differ from U.S. law, please note that your personal information may be transferred to a country and jurisdiction that does not have the same data protection laws as your jurisdiction. When you register for use with Supabase you have the option of where you store your information and we will not transfer it without providing information to you in advance.</p><p>Supabase cares about the security of your information and uses commercially reasonable physical, technical and organizational measures designed to preserve the integrity and security of all information we collect. However, no security system is impenetrable, and we cannot guarantee the security of our systems 100%. In the event that any information under our control is compromised as a result of a breach of security, we will take reasonable steps to investigate the situation and where appropriate, notify those individuals whose information may have been compromised and take other steps, in accordance with any applicable laws and regulations.</p><h2 id="6-links-to-third-party-websites-and-services">
      6. Links to Third-Party Websites and Services
    </h2><p>For your convenience, our Site may provide links to third-party websites or services that we do not own or operate. We are not responsible for the practices employed by any websites or services linked to or from the services, including the information or content contained within them. Your browsing and interaction on any other website or service are subject to the applicable third party’s rules and policies, not ours. If you are using a third-party website or service, you do so at your own risk. We encourage you to review the privacy policies of any site or service before providing any personal information.</p><h2 id="7-childrens-privacy">
      7. Children’s Privacy
    </h2><p>Our services are not intended for children under the age of 13. We do not knowingly solicit or collect personal information from children under the age of 13. If we learn that any personal information has been collected inadvertently from a child under 13, we will delete the information as soon as possible. If you believe that we might have collected information from a child under 13, please contact us at <a href="mailto:privacy@supabase.io">privacy@supabase.io</a>.</p><h2 id="8-changes-to-privacy-notice">
      8. Changes to Privacy Notice
    </h2><p>We reserve the right to change this Privacy Notice from time to time in our sole discretion. We will notify you about material changes in the way we treat personal data by sending a notice to the primary email address specified in your Supabase account and/or by placing a prominent notice on our Site. It is your responsibility to review this Privacy Notice periodically. When we do change the Privacy Notice, we will also revise the "last modified" date.</p><h2 id="9-contact-us">
      9. Contact Us
    </h2><p>For additional inquiries about this Privacy Notice, please send us an email at <a href="mailto:privacy@supabase.io">privacy@supabase.io</a>.</p><p>This Privacy Notice was last modified on 27th March 2021</p><h2 id="privacy-disclosures-for-the-european-economic-area-united-kingdom-and-switzerland">
      Privacy disclosures for the European economic area, United Kingdom, and Switzerland.
    </h2><p>While we are primarily based in the United States, Supabase maintains operations in Europe and may direct our services to individuals located in the European Economic Area ("<strong><em>EEA</em></strong>"), United Kingdom and Switzerland, including through our Site <a href="/">supabase.com</a> (collectively, our "<strong><em>European Services</em></strong>"). The following disclosures ("<strong><em>Privacy Disclosures</em></strong>") apply to our processing of personal data in connection with our European Services.</p><p>Supabase, Inc. is the data controller responsible for the processing of personal data in connection with our European Services. This means that we determine and are responsible for how your personal information is used.</p><p><strong>Personal Data:</strong> When we use the term "personal data" in this section, we mean information relating to an identified or identifiable natural person.</p><h3 id="1-personal-data-we-collect-from-you-when-you-use-the-supabase-european-services-and-how-we-use-it">
      1. Personal data we collect from you when you use the Supabase European Services, and how we use it.
    </h3><p>We collect the categories of personal data that you voluntarily submit directly to us when you use the European Services, as set forth in our Privacy Notice under the section entitled <strong>Information We Collect and Our Use</strong>. The table at <strong>Annex 1</strong> sets out in detail the categories of personal data we collect about you and how we use that information when you use the European Services, as well as the legal basis which we rely on to process the personal information and recipients of that personal information.</p><h3 id="2-information-we-collect-about-you-automatically">
      2. Information we collect about you automatically.
    </h3><p>We also automatically collect personal information indirectly about how you access and use the European Services, and information about the device you use to access the European Services. For example, we may collect:</p><p>(a) information about the features you use and the pages you view on the European Services;</p><p>(b) information about your device (such as your IP address, device identifier, device type, model and manufacturer); and</p><p>(c) information about your usage patterns (such as how often you use the Supabase European Services and your language settings).</p><p>We use this information to provide you the features and functionality of the European Services, to monitor and improve the European Services and to develop new services.</p><p>The table at <strong>Annex 2</strong> sets out further information about the categories of personal information we collect about you automatically and how we use that information. The table also lists the legal basis which we rely on to process the personal information and recipients of that personal information.</p><p>We may link or combine the personal information we collect about you and the information we collect automatically.</p><p>We may anonymise and aggregate any of the personal information we collect (so that it does not directly identify you). We may use anonymised information for purposes that include testing our IT systems, research, data analysis, improving the Supabase European Services. We may also share such anonymised and aggregated information with others.</p><h3 id="3-how-long-will-we-store-your-personal-information">
      3. How long will we store your personal information
    </h3><p>We will usually store the personal information we collect about you for no longer than necessary for the purposes set out in Annex 1 and Annex 2, in accordance with our legal obligations and legitimate business interests.</p><p>The criteria used to determine the period for which personal information about you will be retained varies depending on the legal basis under which we process the personal information:</p><ol>
      <li><strong>Legitimate Interests.</strong> Where we are processing personal information based on our legitimate interests, we generally will retain such information for a reasonable period of time based on the particular interest, taking into account the fundamental interests and the rights and freedoms of data subjects.</li>
      <li><strong>Consent.</strong> Where we are processing personal information based on your consent, we generally will retain the information until you withdraw your consent, or otherwise for the period of time necessary to fulfill the underlying agreement with you or provide you with the applicable service for which we process that personal information.</li>
      <li><strong>Contract.</strong> Where we are processing personal information based on contract, we generally will retain the information for the duration of the contract plus some additional limited period of time that is necessary to comply with law or that represents the statute of limitations for legal claims that could arise from the contractual relationship.</li>
      <li><strong>Legal Obligation.</strong> Where we are processing personal information based on a legal obligation, we generally will retain the information for the period of time necessary to fulfill the legal obligation.</li>
      <li><strong>Legal Claim.</strong> We may need to apply a "legal hold" that retains information beyond our typical retention period where we face threat of legal claim.&nbsp; In that case, we will retain the information until the hold is removed, which typically means the claim or threat of claim has been resolved.</li>
    </ol><p>In all cases, in addition to the purposes and legal bases, we consider the amount, nature and sensitivity of the personal information, as well as the potential risk of harm from unauthorized use or disclosure of your personal information.</p><h3 id="4-recipients-of-personal-information">
      4. Recipients of Personal Information
    </h3><p>In addition to the recipients listed in Annexes 1 and 2, we may also share your personal information with the following (as required in accordance with the uses set out in Annexes 1 and 2):</p><ol>
      <li><strong>Service providers and advisors</strong>: we may share your personal information with third party vendors and other service providers that perform services for us or on our behalf, which may include providing professional services, such as legal and accounting services, mailing, email or chat services, fraud prevention, web hosting, or providing analytic services.</li>
      <li><strong>Affiliates</strong>. Other companies owned by or under common ownership as Supabase, including our subsidiaries (i.e., any organization we own or control) and our ultimate holding company (i.e., any organization that owns or controls us) and any subsidiaries it owns. These companies will use your personal information in the same way as we can under these Privacy Disclosures.</li>
      <li><strong>Purchasers and third parties in connection with a business transaction</strong>: your personal information may be disclosed to third parties in connection with a transaction, such as a merger, sale of assets or shares, reorganization, financing, change of control or acquisition of all or a portion of our business.</li>
      <li><strong>Law enforcement, regulators and other parties for legal reasons</strong>: we may share your personal information with third parties as required by law or if we reasonably believe that such action is necessary to (i) comply with the law and the reasonable requests of law enforcement; (ii) detect and investigate illegal activities and breaches of agreements, including our Terms; and/or (iii) exercise or protect the rights, property, or personal safety of Supabase, its users or others.</li>
    </ol><h3 id="5-marketing-and-advertising">
      5. Marketing and Advertising
    </h3><p>From time to time we may contact you with information about our services, including sending you marketing messages and asking for your feedback on our services. Most marketing messages we send will be by email. For some marketing messages, we may use personal information we collect about you to help us determine the most relevant marketing information to share with you.</p><p>We will only send you marketing messages if you have given us your consent to do so. You can withdraw your consent at a later date by clicking on the unsubscribe link at the bottom of our marketing emails or by updating your preferences via your account on the Site.</p><h3 id="6-storing-and-transferring-your-personal-information">
      6. Storing and transferring your personal information
    </h3><p><strong>Security</strong>. We implement appropriate technical and organizational measures to protect your personal information against accidental or unlawful destruction, loss, change or damage. All personal information we collect will be stored by our cloud hosting provider on secure servers. We will never send you unsolicited emails or contact you by phone requesting credit or debit card information or national identification numbers.</p><p><strong>International Transfers of your Personal Information</strong>. The personal information we collect may be transferred to and stored in countries outside of the jurisdiction you are in where we and our third party service providers have operations. If you are located in the EEA, United Kingdom or Switzerland, your personal information may be processed outside of those regions, including in the United States.</p><p>In the event of such a transfer, we ensure that: (i) the personal information is transferred to countries recognized as offering an equivalent level of protection; or (ii) the transfer is made pursuant to appropriate safeguards, such as standard data protection clauses adopted by the European Commission.</p><p>If you wish to enquire further about these safeguards used, please contact us using the details set out at the end of these Privacy Disclosures.</p><h3 id="7-profiling">
      7. Profiling
    </h3><p>We may analyze personal data we have collected about you to create a profile of your interests and send product updates. We may also use personal data about you to detect and reduce fraud.</p><h3 id="8-your-rights-in-respect-of-your-personal-information">
      8. Your rights in respect of your personal information
    </h3><p>In accordance with applicable privacy law, you have the following rights in respect of your personal information that we hold:</p><ol>
      <li>
        <strong>Right of access</strong>. You have the right to obtain:<!-- -->
        <ol>
          <li>confirmation of whether, and where, we are processing your personal information;</li>
          <li>information about the categories of personal information we are processing, the purposes for which we process your personal information and information as to how we determine applicable retention periods;</li>
          <li>information about the categories of recipients with whom we may share your personal information; and</li>
          <li>a copy of the personal information we hold about you.</li>
        </ol>
      </li>
      <li><strong>Right of portability</strong>. You have the right, in certain circumstances, to receive a copy of the personal information you have provided to us in a structured, commonly used, machine-readable format that supports re-use, or to request the transfer of your personal data to another person.</li>
      <li><strong>Right to rectification</strong>. You have the right to obtain rectification of any inaccurate or incomplete personal information we hold about you without undue delay.</li>
      <li><strong>Right to erasure</strong>. You have the right, in some circumstances, to require us to erase your personal information without undue delay if the continued processing of that personal information is not justified.</li>
      <li><strong>Right to restriction</strong>. You have the right, in some circumstances, to require us to limit the purposes for which we process your personal information if the continued processing of the personal information in this way is not justified, such as where the accuracy of the personal information is contested by you.</li>
      <li><strong>Right to withdraw consent</strong>. There are certain circumstances where we require your consent to process your personal information. In these instances, and if you have provided consent, you have the right to withdraw your consent. If you withdraw your consent, this will not affect the lawfulness of our use of your personal information before your withdrawal.</li>
    </ol><p><strong>You also have the right to object to any processing based on our legitimate interests where there are grounds relating to your particular situation. There may be compelling reasons for continuing to process your personal information, and we will assess and inform you if that is the case. You can object to marketing activities for any reason.</strong></p><p>You also have the right to lodge a complaint to your local data protection authority. If you are based in the European Union, information about how to contact your local data protection authority is available <a href="http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm">here</a>. If you are based in the UK or Switzerland, your local data protection authorities are the UK Information Commissioner's Office (<a href="https://ico.org.uk/global/contact-us/">https://ico.org.uk/global/contact-us/</a>) and the Swiss Federal Data Protection and Information Commissioner (<a href="https://www.edoeb.admin.ch/edoeb/en/home/the-fdpic/contact/address.html">https://www.edoeb.admin.ch/edoeb/en/home/the-fdpic/contact/address.html</a>).</p><p>If you wish to exercise one of these rights, please contact us using the contact details at the end of these Privacy Disclosures.</p><p>Due to the confidential nature of data processing we may ask you to provide proof of identity when exercising the above rights. This can be done by providing a scanned copy of a valid identity document or a signed photocopy of a valid identity document.</p><h3 id="9-cookies-and-similar-technologies-used-on-our-european-services">
      9. Cookies and similar technologies used on our European Services
    </h3><p>Our European Services uses cookies and similar technologies such as pixels and Local Storage Objects (LSOs) like HTML5 (together "<strong><em>cookies</em></strong>") to distinguish you from other users of our European Services. This helps us to provide you with a good experience when you browse our European Services and also allows us to monitor and analyse how you use and interact with our European Services so that we can continue to improve our European Services.</p><p>Cookies are pieces of code that allow for personalization of our European Services experience by saving your information such as user ID and other preferences. A cookie is a small data file that we transfer to your computer's hard disk for record-keeping purposes.</p><p>We use the following types of cookies:</p><ol>
      <li><strong>Strictly necessary cookies</strong>. These are cookies that are required for the operation of our European Services. They include, for example, cookies that enable you to log into secure areas of our European Services.</li>
    </ol><p>Please see <strong>Annex 3</strong> for more information about the cookies we use on the European Services.</p><p>Most browsers also allow you to change your cookie settings to block certain cookies. Depending on your mobile device and operating system, you may not be able to delete or block all cookies. Please note that if you choose to refuse all cookies you may not be able to use the full functionality of our European Services. These settings will typically be found in the "options" or "preferences" menu of your browser. In order to understand these settings, the following links may be helpful, otherwise you should use the "Help" option in your browser for more details.</p><ul>
      <li><a href="https://support.microsoft.com/en-gb/help/278835/how-to-delete-cookie-files-in-internet-explorer">Cookie settings in Internet Explorer</a></li>
      <li><a href="http://support.mozilla.org/en-US/kb/cookies">Cookie settings in Firefox</a></li>
      <li><a href="https://support.google.com/chrome/answer/95647?hl=en">Cookie settings in Chrome</a></li>
      <li><a href="https://support.apple.com/en-gb/guide/safari/manage-cookies-and-website-data-sfri11471/mac">Cookies settings in Safari web</a> and&nbsp;<a href="https://support.apple.com/en-gb/HT201265">iOS</a>.</li>
    </ul><p>If you would like to find out more about cookies and other similar technologies, please visit <a href="http://www.allaboutcookies.org">allaboutcookies.org</a>.</p><p>Please note that deleting or blocking cookies may not be effective for all types of tracking technologies, such as Local Storage Objects (LSOs) like HTML5.</p><h3 id="10-tracking-technologies-used-in-our-emails">
      10. Tracking technologies used in our emails
    </h3><p>Our emails may contain tracking pixels that identify if and when you have opened an email that we have sent you, how many times you have read it and whether you have clicked on any links in that email. This helps us measure the effectiveness of our marketing email campaigns, make the emails we send to you more relevant to your interests and to understand if you have opened and read any important administrative emails we might send you.</p><p>Most popular email clients will allow you to block these pixels by disabling certain external images in emails. You can do this through the settings on your email client – these generally give you the option of choosing whether emails will display "remote images", "remote content" or "images" by default.</p><p>Some browsers also give you the option of downloading and installing extensions that block pixels and other tracking technologies.</p>
  </div>
</template>

<style>

</style>
